Default: &defaults
  user: memopad
  password: memopad
  host: localhost
  port: 5432
  database: memopad
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: memopad_test
  <<: *defaults

Staging:
  database: memopad_staging
  poolsize: 100
  <<: *defaults

Production:
  database: memopad_production
  poolsize: 100
  <<: *defaults
